Location.find_or_initialize_by(name: 'Bonsoir').update_attributes(link: 'https://bonsoir.ch/agenda/')
Location.find_or_initialize_by(name: 'Turnhalle').update_attributes(link: 'https://www.turnhalle.ch/')
Location.find_or_initialize_by(name: 'ISC').update_attributes(link: 'https://isc-club.ch/')
Location.find_or_initialize_by(name: 'Bad Bonn').update_attributes(link: 'http://club.badbonn.ch/konzerte')
Location.find_or_initialize_by(name: 'Bierhübeli').update_attributes(link: 'http://www.bierhuebeli.ch/veranstaltungen/')
